# Generated by Django 3.0.7 on 2020-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='about',
            new_name='type',
        ),
        migrations.AddField(
            model_name='about',
            name='blogs',
            field=models.ManyToManyField(to='blog.BlogPost'),
        ),
    ]
